//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by interf.rc
//
#define IDC_MYICON                      2
#define ID_OVERWRITE_ALL                3
#define ID_SKIP                         4
#define ID_SKIP_ALL                     5
#define IDD_INTERF_DIALOG               102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_INTERF                      107
#define IDI_SMALL                       108
#define IDC_INTERF                      109
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_DIALOG2                     130
#define IDI_OFOLDER                     140
#define IDI_HDD                         141
#define IDI_FOLDER                      142
#define IDI_FD3_5                       143
#define IDI_FD5_25                      144
#define IDI_FD3_5_16                    145
#define IDI_HDD_16                      146
#define IDI_FOLDER_16                   147
#define IDI_OFOLDER_16                  148
#define IDI_FD5_25_16                   149
#define IDI_COMPUTER_16                 150
#define IDI_REGFILE                     151
#define IDI_REGFILE_16                  152
#define IDI_CHARFILE_16                 154
#define IDI_BLOCKFILE_16                155
#define IDI_FIFOFILE_16                 156
#define IDI_SOCKFILE_16                 157
#define IDI_LNKFILE_16                  158
#define IDI_BLOCKFILE                   159
#define IDI_CHARFILE                    160
#define IDI_FIFOFILE                    161
#define IDI_LNKFILE                     162
#define IDI_SOCKFILE                    163
#define IDD_DIALOG_MI_PROPS_PAGE1       164
#define IDD_DIALOG_MI_PROPS             165
#define IDD_DIALOG_MI_PROPS_PAGE2       166
#define IDD_DIALOG_FILE_PROPS           167
#define IDD_DIALOG_FILES_PROPS          168
#define IDI_FILES                       169
#define IDD_DIALOG_WARNING              170
#define IDD_DIALOG_COPYFILE             171
#define IDD_DIALOG_OVERWRITE            174
#define IDD_ABOUT                       175
#define IDR_POPUP1                      178
#define IDR_POPUPS                      178
#define IDR_MENU1                       179
#define IDD_DIALOG_SHOW                 180
#define IDR_MENU_VIEW                   181
#define IDD_DIALOG_FIND                 182
#define IDD_DIALOG_READFILE             184
#define IDC_TREE1                       1004
#define IDC_CHECK_NAME                  1006
#define IDC_CHECK_TYPE                  1007
#define IDC_CHECK_SIZE                  1008
#define IDC_CHECK_RIGHTS                1009
#define IDC_CHECK_CTIME                 1010
#define IDC_STATIC_INODES_COUNT         1010
#define IDC_CHECK_MTIME                 1011
#define IDC_STATIC_FREE_INODES_COUNT    1011
#define IDC_CHECK_ATIME                 1012
#define IDC_STATIC_INODES_PER_GROUP     1012
#define IDC_CHECK_USER                  1013
#define IDC_STATIC_BLOCK_COUNT          1013
#define IDC_CHECK_GROUP                 1014
#define IDC_STATIC_FREE_BLOCK_COUNT     1014
#define IDC_STATIC_R_BLOCK_COUNT        1015
#define IDC_STATIC_BLOCK_SIZE           1016
#define IDC_STATIC_MTIME                1017
#define IDC_STATIC_MNT_COUNT            1018
#define IDC_STATIC_MAX_MNT_COUNT        1019
#define IDC_TAB1                        1021
#define IDC_STATIC_FILE_NAME            1022
#define IDC_STATIC_TYPE                 1023
#define IDC_STATIC_ATTR                 1025
#define IDC_STATIC_I_SIZE               1026
#define IDC_STATIC_CTIME                1027
#define IDC_STATIC_ATIME                1028
#define IDC_STATIC_SUID                 1029
#define IDC_STATIC_SGID                 1030
#define IDC_STATIC_I_LINKS_COUNT        1031
#define IDC_STATIC_SPLITTER             1032
#define IDC_STATIC_EXTENDED_TEXT        1033
#define IDC_STATIC_ICON                 1034
#define IDC_STATIC_EXTENDED             1035
#define IDC_STATIC_STATE                1036
#define IDC_STATIC_VOLUME               1037
#define IDC_STATIC_FILES                1038
#define IDC_STATIC_MSG_TITLE1           1039
#define IDC_STATIC_MSG_TITLE1_TEXT      1040
#define IDC_STATIC_WARNIG_TEXT          1042
#define IDC_STATIC_LINUXNAME            1043
#define IDC_STATIC_WINDOWSNAME          1044
#define IDC_PROGRESS1                   1045
#define IDC_STATIC_FILENUM              1046
#define ID_OVERWRITE                    1048
#define IDC_STATIC_OVERWRITE_TEXT       1049
#define ID_CANCEL                       1051
#define IDC_FIND_CHECK1                 1059
#define IDC_FIND_CHECK2                 1060
#define IDC_FIND_COMBO1                 1061
#define IDC_STATIC_FILE                 1062
#define IDC_ABOUT_MAIL                  1063
#define IDM_PROP                        32776
#define IDM_PROPS                       32776
#define IDM_COPY                        32777
#define IDM_REFRESH                     32778
#define IDM_FB_SMALLICON                32779
#define IDM_FB_LIST                     32780
#define IDM_FB_REPORT                   32781
#define IDM_SORT_NAME                   32782
#define IDM_SORT_BY_NAME                32782
#define IDM_FB_ICON                     32784
#define IDM_OPTIONS                     32785
#define IDM_SORT_BY_SIZE                32786
#define IDM_SORT_BY_NONE                32788
#define IDM_SORT_BY_TYPE                32791
#define IDM_SORT_BY_DATE                32792
#define ID_DFG                          32805
#define IDM_STATUSBAR                   32806
#define IDM_VIEW_EXIT                   32807
#define IDM_VIEW_SELECTALL              32809
#define IDM_VIEW_FIND                   32810
#define IDM_VIEW_CODE_CP1251            32811
#define IDM_VIEW_CODE_KOI8              32812
#define IDM_VIEW_FONT                   32813
#define IDM_VIEW_COPY                   32814
#define IDM_VIEW_FINDMORE               32817
#define IDM_VIEW                        32818
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
