#ifndef __TEXT_H__
#define __TEXT_H__
#include <tchar.h>

enum Lang {LangRU};

const DWORD MAX_MESSAGE_LEN = 150;

enum MessageEnum {
	MSG_FILETYPE_REG,
		MSG_FILETYPE_DIR,
		MSG_FILETYPE_CHR,
		MSG_FILETYPE_BLK,
		MSG_FILETYPE_FIFO,
		MSG_FILETYPE_SOCK,
		MSG_FILETYPE_LNK,
		MSG_SUPERBLOCK,
		MSG_ROOTDIR,
		MSG_UNKNOWN,
		MSG_PROPERTIES,
		MSG_FSERRORS,
		MSG_NOFSERRORS,
		MSG_CONTAIN,
		MSG_FILESANDFOLDERS,
		MSG_ERROR,
		MSG_DEVICENOTREADY,
		MSG_DIRSANDFILES,
		MSG_DIRS,
		MSG_FILES,
		MSG_SUMFILESIZE,
		MSG_BYTE,
		MSG_KILOBYTE,
		MSG_MEGABYTE,
		MSG_GIGABYTE,
		MSG_CHOOSEONEDISK,
		MSG_WARNING,
		MSG_DIRECTACCESSDENIED,
		MSG_DISKCHANGED,
		MSG_BROWSETITLE,
		MSG_ALLFILES,
		MSG_ACCESSDENIED,
		MSG_DISKFULL,
		MSG_DEVICE,
		MSG_LINK,
        MSG_OBJECTS,
        MSG_SELECTED,
        MSG_FREEONDISK,
        MSG_NAMETOOLONG,
        MSG_LIBNOTFOUND,
		MSG_TOOMANYVIEWS,
		MSG_VIEWTITLE,
		MSG_COLANDROW,
		MSG_SAMPLENOTFOUND,
		MSG_STRINGNOTFOUND,
		MSG_BADPARTITIONTABLE,
		MSG_NOMEMORYFORVIEW,
		MAX_MSG
};

const TCHAR MessageRU[MAX_MSG][MAX_MESSAGE_LEN] =
{	"файл",
	"каталог",
	"символьное у-во",
	"блочное у-во",
	"канал fifo",
	"сокет",
	"ссылка",
	"Суперблок",
	"Корневой каталог",
	"Неизвестно",
	"Свойства",
	"Ошибки есть",
	"Oшибок нет",
	"Содержит:",
	"файлов/каталогов -",
	"Ошибка !",
	"Нет доступа к %s.\n\nУстройство не готово.",
	"Каталогов: %lu; файлов: %lu",
	"Каталогов: %lu",
	"Файлов: %lu",
	"Объем файлов:",
	"байт",
    "KБ",
    "MБ",
    "ГБ",
	"Необходимо выбрать один диск !",
	"Предупреждение",
	"Прямой доступ к одному или нескольким дискам запрещен Администратором\nЕсли на этих дисках есть разделы ext2fs, они не будут видны.",
	"Носитель в устройстве %s был заменен.\nПеремонтировать файловую систему ?",
	"Копировать в:",
	"Все файлы",
	"В доступе к %s отказано.",
	"Недостаточно свободного места на диске %s",
	"Устройство:",
	"Ссылка:",
    "Объектов:",
    "Выделено объектов:",
    "Свободно на диске:",
    "Невозможно создать файл или каталог - слишком длинное имя",
    "Отсутствует динамическая библиотека %s.\n      Продолжение работы невозможно.",
	"Слишком много окон просмотра",
	"Просмотр - ",
	"Стр %u/%u, Ст %u",
	"Не найдено",
	"Строка не найдена",
	"Ошибка чтения таблицы разделов диска hd%c",
	"Недостаточно памяти для просмотра файла"
};	


TCHAR *Message(DWORD N);

#endif //__TEXT_H__